---
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v6.0.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: mixed-line-ending
            args: [--fix, lf]
          - id: check-yaml
          - id: check-added-large-files
            args: [--maxkb=2000]
          - id: check-merge-conflict
          - id: check-case-conflict
          - id: check-toml

    - repo: local
      hooks:
          - id: toml-sort-fix
            name: toml-sort-fix
            entry: toml-sort
            args: [--in-place]
            language: python
            types: [toml]
            additional_dependencies: [toml-sort>=0.23.1]

          - id: toml-sort
            name: toml-sort
            entry: toml-sort
            args: [--check]
            language: python
            types: [toml]
            additional_dependencies: [toml-sort>=0.23.1]

    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.14.9
      hooks:
          - id: ruff
            args: [
              --fix,
              --unsafe-fixes,
              --select, ALL,
              --ignore, ANN401,
              --ignore, C901,
              --ignore, COM812,
              --ignore, D203,
              --ignore, D211,
              --ignore, D213,
              --ignore, E501,
              --ignore, ERA001,
              --ignore, F722,
              --ignore, F821,
              --ignore, G004,
              --ignore, ISC001,
              --ignore, N812,
              --ignore, PERF203,
              --ignore, PERF401,
              --ignore, PLR0911,
              --ignore, PLR0912,
              --ignore, PLR0913,
              --ignore, PLR0915,
              --ignore, PLR2004,
              --ignore, PLW2901,
              --ignore, RUF012,
              --ignore, S603,
              --ignore, S607,
              --ignore, SIM115,
              --ignore, SLF001,
              --ignore, T201,
              --ignore, TCH010,
              --ignore, TD003,
              --ignore, TRY301,
            ]
          - id: ruff-format

    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v1.19.0
      hooks:
          - id: mypy
            name: mypy
            entry: mypy
            language: python
            types_or: [python, pyi]
            require_serial: true
            args: [
              --ignore-missing-imports,
              --scripts-are-modules,
              --install-types,
              --non-interactive,
              --warn-unused-ignores,
              --show-error-codes,
              --check-untyped-defs,
              --disallow-incomplete-defs,
              --explicit-package-bases,
              --warn-redundant-casts,
              --strict-equality,
              --strict-equality-for-none,
              --follow-untyped-imports,
            ]
            additional_dependencies:
                - pydantic
                - types-requests
